#!/usr/bin/python3
import sys
import subprocess

PATH_TUPLE = sys.argv[0].rpartition("/")
UTILS = "{}/../../utils/".format(PATH_TUPLE[0])

INSTALL_LOCATION = "/usr/local/lib/java7"
SYM_LINK_LOCATION = "/usr/local/bin/java"
BUNDLE_PATH = "{}{}bundle".format(PATH_TUPLE[0], PATH_TUPLE[1])

server_addr = sys.argv[1]
server_usr = sys.argv[2]
server_pass = sys.argv[3]

print("Server address:", server_addr)
print("User name:", server_usr)
print("Install location:", INSTALL_LOCATION)

try:
    print("Transfer installation bundle to remote server.")
    result = subprocess.call(["{}push".format(UTILS),
        server_addr, server_usr, server_pass, BUNDLE_PATH, INSTALL_LOCATION])
    if result != 0:
        raise OSError("Fail to transfer installation bundle to remote server.")

    print("Create symbolyc link to Java executable file.")
    result = subprocess.call(["{}symlink_create".format(UTILS),
        server_addr, server_usr, server_pass, 
        "{}/bin/java".format(INSTALL_LOCATION), SYM_LINK_LOCATION])
    if result != 0:
        raise OSError("Fail to create symbolic link to Java.")

    print("Update system variables.")
    result = subprocess.call(["{}sysvar_update".format(UTILS), 
        server_addr, server_usr, server_pass, "JAVA_HOME", INSTALL_LOCATION])
    if result != 0:
        raise OSError("Fail to update system variables.")
except OSError as err:
    print("OS Error: {}".format(err))
    print("Installation fail.")
    exit(1)

print("Java v.7. Successfully installed.")
print("Remote machine should be rebooted to apply some chenges.")
input("Reboot remote machine and press 'Enter' to continue.")
exit(0)
