#!/usr/bin/python3
import sys
import subprocess

PATH_TUPLE = sys.argv[0].rpartition("/")

if len(sys.argv) == 1:
    print("""\

***************************************
Util to push content to remote machine.
***************************************
  Use with follow format:
    {} <server_addr> <server_user> <server_pass> <local_path> <remote_path>
  where
    server_addr - remote server address
    server_user - remote server user
    server_pass - remote server password
    local_path  - path to content on local machine
    remote_path - path to content on remote machine
""".format(PATH_TUPLE[2]))

server_addr = sys.argv[1]
server_usr = sys.argv[2]
server_pass = sys.argv[3]

path_local = sys.argv[4]
path_remote = sys.argv[5]

print("Try to push content to remote machine:")
print("  from {}".format(path_local))
print("  to {addr}:{path}".format(addr=server_addr, path=path_remote))

try:
    result = subprocess.call(["sshpass", "-p", server_pass,
        "scp", "-r", path_local, 
        "{user}@{addr}:{path}".format(user=server_usr, addr=server_addr, path=path_remote)])
    if result != 0:
        raise OSError("Fail code received from system command. Result code: {}".format(result))
except OSError as err:
    print("OS Error: {}".format(err))
    print("Fail to push content to remote server.")
    exit(1)

print("Content pushed success.")
exit(0)
